DROP TABLE requests;
DROP TABLE users;

CREATE TABLE IF NOT EXISTS users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name     VARCHAR(256)                            NOT NULL,
    email         VARCHAR(128)                            NOT NULL,
    user_admin    BOOLEAN                                 DEFAULT (false),
    user_operator BOOLEAN                                 DEFAULT (false),
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text_request VARCHAR(1024)                           NOT NULL,
    created_on   TIMESTAMP                               NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    status       VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (request_id),
    CONSTRAINT fk_user_id_requests FOREIGN KEY (user_id) REFERENCES users (user_id)
);

INSERT INTO USERS
VALUES (1, 'Andrey', 'mmm@mail.ru');

INSERT INTO USERS
VALUES (2, 'Alex', 'aaa@mail.ru');

INSERT INTO USERS
VALUES (3, 'Anna', 'sss@mail.ru', true, true);

INSERT INTO USERS
VALUES (4, 'Tatiana', 'qwe@mail.ru', true);

INSERT INTO USERS
VALUES (5, 'Ivan', 'asd@mail.ru');

INSERT INTO USERS
VALUES (6, 'Elizaveta', 'hgnf@mail.ru', false, true);

INSERT INTO USERS
VALUES (7, 'Sergey', 'cdscsv@mail.ru');

INSERT INTO USERS
VALUES (8, 'Igor', 'dsvdv@mail.ru');

INSERT INTO USERS
VALUES (9, 'Olga', 'fddnbd@mail.ru', true, true);

INSERT INTO USERS
VALUES (10, 'Elena', 'vscsdo@mail.ru', false, true);

INSERT INTO USERS
VALUES (11, 'Valentina', 'comlsv@mail.ru');